---
permalink: online-help/reference-snapmirror-and-vault-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: Los eventos de relaciones de SnapMirror y almacén le proporcionan información sobre el estado de las relaciones de SnapMirror y almacén asíncrono para poder realizar una supervisión de posibles problemas. Los eventos se agrupan por área de impacto e incluyen el nombre del evento y de captura, el nivel de impacto, el tipo de origen y la gravedad. 
---
= Eventos de relaciones de SnapMirror y almacén
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los eventos de relaciones de SnapMirror y almacén le proporcionan información sobre el estado de las relaciones de SnapMirror y almacén asíncrono para poder realizar una supervisión de posibles problemas. Los eventos se agrupan por área de impacto e incluyen el nombre del evento y de captura, el nivel de impacto, el tipo de origen y la gravedad.



== Zona de impacto: Protección

|===
| Nombre del evento(nombre de la captura) | Nivel de impacto | Tipo de origen | Gravedad 


 a| 
Reflejo asíncrono y almacén en mal estado(ocumEvtMirrorRelationship relación depósito Unheavy)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Advertencia



 a| 
Reflejo asíncrono y almacén roto-off (ocumEvtMirrorRelationship ationshipStateBrokenoff)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Error



 a| 
Error en el reflejo asíncrono y la inicialización del almacén (error de ocumEvtMirrorRelationship InitializeFailed)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Error



 a| 
Error en la actualización de reflejo asíncrono y almacén (ocumEvtMirrorRelationship UpdateFailed)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Error



 a| 
Error de desfase de reflejo asíncrono y almacén (ocumEvtMirrorRelationship shipLagError)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Error



 a| 
Advertencia de desfase de reflejo asíncrono y almacén (ocumEvtMirrorRelationship relación shipLagWarning)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Advertencia



 a| 
Error en la resincronización de reflejo asíncrono y almacén (ocumEvtMirrorRelationshipResyncFailed)
 a| 
Riesgo
 a| 
Relación de SnapMirror
 a| 
Error

|===