---
permalink: online-help/task-specifying-the-destination-location-for-snapshot-backups.html 
sidebar: sidebar 
keywords:  
summary: Puede configurar la ubicación de destino para backups de Snapshot de Unified Manager en un volumen que ya se configuró en uno de los clústeres de ONTAP. Usted define la ubicación desde la consola de mantenimiento de Unified Manager. 
---
= Especificar la ubicación de destino para los backups de Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar la ubicación de destino para backups de Snapshot de Unified Manager en un volumen que ya se configuró en uno de los clústeres de ONTAP. Usted define la ubicación desde la consola de mantenimiento de Unified Manager.



== Antes de empezar

* Debe tener las credenciales de usuario raíz del host Linux en el que está instalado Unified Manager.
* Debe tener un ID de usuario y una contraseña autorizados para iniciar sesión en la consola de mantenimiento del servidor de Unified Manager.
* Debe tener la dirección IP de gestión del clúster, el nombre de la máquina virtual de almacenamiento, el nombre del volumen, y el nombre de usuario y la contraseña del sistema de almacenamiento.
* Debe haber montado el volumen en el host de Unified Manager y la ruta de montaje debe ser.




== Pasos

. Mediante Secure Shell, conéctese a la dirección IP o al nombre de dominio completo del sistema Unified Manager.
. Inicie sesión en el sistema con el nombre y la contraseña del usuario de mantenimiento (umadmin).
. Introduzca el comando `maintenance_console` Y pulse Intro.
. En la consola de mantenimiento *Menú principal*, introduzca el número de la opción *Restauración de copia de seguridad*.
. Introduzca el número para *Configurar Snapshot Backup de NetApp*.
. Introduzca el número de *Configuración para NFS*.
. Revise la información que necesitará proporcionar y, a continuación, introduzca el número para *introducir detalles de configuración de copia de seguridad*.
. Para identificar el volumen donde se escribirá la snapshot, introduzca la dirección IP de la interfaz de gestión del clúster, el nombre de la máquina virtual de almacenamiento, el nombre del volumen, el nombre de usuario y la contraseña del sistema de almacenamiento y la ruta de montaje.
. Compruebe esta información e introduzca `y`.
+
El sistema ejecuta las siguientes tareas:

+
** Establece la conexión con el clúster
** Detiene todos los servicios
** Crea un nuevo directorio en el volumen y copia los archivos de configuración de la base de datos de Unified Manager
** Elimina los archivos de Unified Manager y crea un enlace simbólico en el nuevo directorio de la base de datos
** Reinicia todos los servicios


. Salga de la consola de mantenimiento e inicie la interfaz de Unified Manager para crear la programación de backup de Snapshot si no lo ha hecho todavía.

