---
permalink: health-checker/task-defining-a-schedule-for-snapshot-backups.html 
sidebar: sidebar 
keywords:  
summary: Puede configurar la programación en la que se crean backups de Unified Manager Snapshot con la interfaz de usuario de Unified Manager. 
---
= Definir una programación para backups de Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar la programación en la que se crean backups de Unified Manager Snapshot con la interfaz de usuario de Unified Manager.



== Antes de empezar

* Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.
* Debe haber configurado la configuración de backup de Snapshot de NetApp desde la consola de mantenimiento para identificar el destino en el que se crearán las snapshots.
* No se deben programar operaciones de backup para que se produzcan inmediatamente después de añadir un clúster nuevo mientras Unified Manager recoge 15 días de datos de rendimiento históricos.




== Acerca de esta tarea

Los backups de Snapshot se crean en solo unos minutos y la base de datos de Unified Manager se bloquea solo durante unos pocos segundos.



== Pasos

. En el panel de navegación izquierdo, haga clic en *General* > *copia de seguridad de la base de datos*.
. En la página *copia de seguridad de la base de datos*, haga clic en *Configuración de copia de seguridad*.
. Introduzca el número máximo de copias Snapshot que desea retener en el campo *recuento de retención*.
+
El valor predeterminado para el número de retención es 10. El número máximo de copias Snapshot viene determinado por la versión del software de ONTAP en el clúster: 1020 para ONTAP 9.4 y posteriores, y 250 para ONTAP 9.3 y versiones anteriores. Puede dejar este campo en blanco para implementar el valor máximo independientemente de la versión de ONTAP.

. Seleccione el botón *Diario programado* o *Semanal programado* y, a continuación, especifique los detalles del programa.
. Haga clic en *aplicar*.




== Resultados

Los archivos de backup de Snapshot se crean según la programación. Puede ver los archivos de copia de seguridad disponibles en la página copia de seguridad de la base de datos.



== Después de terminar

Debido a la importancia de este volumen y de las copias de Snapshot, puede crear una o dos alertas para este volumen, de modo que reciba una notificación cuando:

* El espacio del volumen está lleno al 90%. Utilice el evento *espacio de volumen lleno* para configurar la alerta.
+
Es posible añadir capacidad al volumen con ONTAP System Manager o la interfaz de línea de comandos de ONTAP para que la base de datos de Unified Manager no se quede sin espacio.

* El número de instantáneas está cerca de alcanzar el número máximo. Utilice el evento *demasiadas copias Snapshot* para configurar la alerta.
+
Puede eliminar copias de Snapshot más antiguas con ONTAP System Manager o la interfaz de línea de comandos de ONTAP para que siempre haya espacio para nuevos backups de copias de Snapshot.



Las alertas se configuran en la página Alert Setup.
