---
permalink: data-protection/reference-relationship-last-1-month-transfer-rate-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista relación: La vista tasa de transferencia de 1 mes pasado permite analizar la cantidad de volumen de datos que se transfiere el día a día para los volúmenes en relaciones asíncronas. En esta página también se ofrecen detalles sobre las transferencias diarias de volúmenes y el tiempo necesario para completar la operación de transferencia.' 
---
= Relación: Última vista de tarifa de transferencia de 1 mes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista relación: La vista tasa de transferencia de 1 mes pasado permite analizar la cantidad de volumen de datos que se transfiere el día a día para los volúmenes en relaciones asíncronas. En esta página también se ofrecen detalles sobre las transferencias diarias de volúmenes y el tiempo necesario para completar la operación de transferencia.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta (de estado, rendimiento, capacidad, etc.), realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para limitar la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv`, `.pdf`, o. `.xlsx` archivo. Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

* *Tamaño total de transferencia*
+
Muestra el tamaño total de la transferencia de volumen en gigabytes.

* *Día*
+
Muestra el día en el que se inició la transferencia de volumen.

* *Hora final*
+
Muestra la hora de finalización de la transferencia de volumen con la fecha.


