---
permalink: data-protection/reference-relationship-last-1-month-transfer-status-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Relationship: Last 1 month Transfer Status permite analizar las tendencias de transferencia de volúmenes durante un periodo de tiempo para los volúmenes en relaciones asíncronas. En esta página también se muestra si la transferencia de volumen fue correcta o no.' 
---
= Relación: Vista Estado de transferencia de último 1 mes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Relationship: Last 1 month Transfer Status permite analizar las tendencias de transferencia de volúmenes durante un periodo de tiempo para los volúmenes en relaciones asíncronas. En esta página también se muestra si la transferencia de volumen fue correcta o no.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta (de estado, rendimiento, capacidad, etc.), realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para limitar la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv`, `.pdf`, o. `.xlsx` archivo. Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

* *Volumen de origen*
+
Muestra el nombre del volumen de origen.

* *Volumen de destino*
+
Muestra el nombre del volumen de destino.

* *Tipo de operación*
+
Muestra el tipo de transferencia de volumen.

* *Resultado de funcionamiento*
+
Muestra si la transferencia de volumen se realizó correctamente.

* *Hora de inicio de la transferencia*
+
Muestra la hora de inicio de la transferencia del volumen.

* *Tiempo de finalización de transferencia*
+
Muestra la hora de finalización de la transferencia del volumen.

* *Duración de transferencia*
+
Muestra el tiempo necesario (en horas) para completar la transferencia de volumen.

* *Tamaño de transferencia*
+
Muestra el tamaño (en MB) del volumen transferido.

* *Fuente SVM*
+
Muestra el nombre de la máquina virtual de almacenamiento (SVM).

* *Cluster de origen*
+
Muestra el nombre del clúster de origen.

* *SVM de destino*
+
Muestra el nombre de la SVM de destino.

* *Cluster de destino*
+
Muestra el nombre del clúster de destino.


